apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - node
                - dist/index.js
                - --health
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - node
                - dist/index.js
                - --health
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ include "backend.fullname" $ }}
                  key: {{ $key }}
            {{- end }}
            # Secret environment variables
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.database.name }}
                  key: {{ .Values.secrets.database.key }}
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.stripe.secretKey.name }}
                  key: {{ .Values.secrets.stripe.secretKey.key }}
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.stripe.webhookSecret.name }}
                  key: {{ .Values.secrets.stripe.webhookSecret.key }}
            - name: LIVEKIT_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.livekit.url.name }}
                  key: {{ .Values.secrets.livekit.url.key }}
            - name: LIVEKIT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.livekit.apiKey.name }}
                  key: {{ .Values.secrets.livekit.apiKey.key }}
            - name: LIVEKIT_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.livekit.apiSecret.name }}
                  key: {{ .Values.secrets.livekit.apiSecret.key }}
            - name: GH_ACTIONS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.github.token.name }}
                  key: {{ .Values.secrets.github.token.key }}
                  optional: true
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}